game.AddParticles("particles/raygunmark2.pcf")
PrecacheParticleSystem("raygunmkii_muzzle")
PrecacheParticleSystem("raygunmkii_muzzlecore")
PrecacheParticleSystem("raygunmkii_projectile")
PrecacheParticleSystem("raygunmkii_impact")