game.AddParticles("particles/scavenger.pcf")
	PrecacheParticleSystem("ubersniper_explosion_base")
	PrecacheParticleSystem("ubersniper_victim_redmist")
game.AddParticles("particles/neuro_gore.pcf")
	PrecacheParticleSystem("tank_gore")
